steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/$PROJECT_ID/flask-app', '--platform', 'managed', '--region', 'us-central1']
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'echo "Project ID is $PROJECT_ID"'

images:
- 'gcr.io/$PROJECT_ID/flask-app'

options:
  logging: CLOUD_LOGGING_ONLY
